### ISSUE TITLE
pHash under package org.phash

### ISSUE THREAD

**Issue by franciscbalint** [clearscene/pHash#12]
After I move the classes under a package the following error occurs.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.phash.pHash.pHashInit()V
	at org.phash.pHash.pHashInit(Native Method)
	at org.phash.pHash.<clinit>(pHash.java:13)
```

Line 13
`pHashInit();`

Any ideas?
Thank you.

**Comment by franciscbalint** [comment]
I made it work with reflection api.
Example: https://github.com/0xfib/pHash-Maven-Java
